CREATE TABLE `hiduke` (
	`dayid` SERIAL NOT NULL,
	`day` DATE NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`delet_at` DATETIME DEFAULT NULL,
	PRIMARY KEY (`dayid`)
) ENGINE=InnoDB;
