CREATE TABLE `nikkiinfor` (
	`nikkiid` SERIAL NOT NULL,
	`title` VARCHAR(32) NOT NULL,
	`infor` VARCHAR(1024) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`delet_at` DATETIME DEFAULT NULL,
	PRIMARY KEY (`nikkiid`)
) ENGINE=InnoDB;
